name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        compiler: [gcc, clang]
        include:
          - os: windows-latest
            compiler: msvc
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake g++ clang

      - name: Configure CMake
        run: |
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            cmake -S . -B build
          else
            if [ "${{ matrix.compiler }}" = "clang" ]; then
              cmake -S . -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libstdc++"
            else
              cmake -S . -B build -DCMAKE_CXX_COMPILER=g++
            fi
          fi
        shell: bash

      - name: Build
        run: cmake --build build
